name: Python macOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # New step to install Tcl/Tk (if necessary)
    - name: Install Tcl/Tk
      run: brew install tcl-tk

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --onefile country_quiz.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: mac-executable
        path: dist/*
